[versions]
# Plugins
kotlin = "2.2.10"
spring-boot = "4.0.0"
freefair-lombok = "9.1.0"
openapi-generator = "7.17.0"

# Libraries
slf4j = "2.0.17"
lombok = "1.18.42"
jackson-bom = "2.20.1"
javax-jaxb-api = "2.3.1"
javax-annotation-api = "1.3.2"
jsr305 = "3.0.2"
threeten-jaxb-core = "1.2"
bouncycastle = "1.83"
nimbus-jose-jwt = "10.6"
mapstruct = "1.6.3"
wiremock = "3.13.2"

[libraries]
# Slf4j
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# Lombok
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# Jackson (use as platform/BOM)
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson-bom" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson-dataformat-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml" }
jackson-jaxb-annotations = { module = "com.fasterxml.jackson.module:jackson-module-jaxb-annotations" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }

# XML bind
javax-jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "javax-jaxb-api" }

# Annotations
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation-api" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
threeten-jaxb-core = { module = "io.github.threeten-jaxb:threeten-jaxb-core", version.ref = "threeten-jaxb-core" }

# Crypto
bcprov-jdk18on = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
bcpkix-jdk18on = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbus-jose-jwt" }

# Kotlin
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# MapStruct
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

# Testing
wiremock-standalone = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }

[plugins]
# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

# Spring Boot
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

# Lombok (Freefair)
freefair-lombok = { id = "io.freefair.lombok", version.ref = "freefair-lombok" }

# OpenAPI Generator
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
